"""
Orchestrator: fetch data → fit model → write src/odds.ts.

Run from the repo root with:

    python model/generate_odds.py            # uses Dixon-Coles + xG (recommended)
    python model/generate_odds.py --no-xg    # falls back to actual goals
    python model/generate_odds.py --bayesian # uses the Bayesian model (slow)

The script knows which 12 fixtures to predict because they're hard-coded in
src/data.ts. We mirror that list here (REMAINING_FIXTURES) — keep them in
sync if a fixture changes.

Output: a fresh src/odds.ts with provenance comments showing which model and
when. Manual overrides in odds.ts will be wiped — if you want a manual override
to persist, edit MANUAL_OVERRIDES below.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "model"))

from dixon_coles import DixonColesModel  # noqa: E402
from fetch_data import fetch_all          # noqa: E402

ODDS_TS_PATH = ROOT / "src" / "odds.ts"

# Mirror of the 12 toggleable fixtures in src/data.ts.
# (id, home_short, away_short)
REMAINING_FIXTURES: list[tuple[str, str, str]] = [
    ("M35-AVL-TOT", "AVL", "TOT"),
    ("M35-CHE-NFO", "CHE", "NFO"),
    ("M36-TOT-LEE", "TOT", "LEE"),
    ("M36-WHU-ARS", "WHU", "ARS"),
    ("M36-NFO-NEW", "NFO", "NEW"),
    ("M37-CHE-TOT", "CHE", "TOT"),
    ("M37-NEW-WHU", "NEW", "WHU"),
    ("M37-MUN-NFO", "MUN", "NFO"),
    ("M37-LEE-BHA", "LEE", "BHA"),
    ("M38-TOT-EVE", "TOT", "EVE"),
    ("M38-WHU-LEE", "WHU", "LEE"),
    ("M38-NFO-BOU", "NFO", "BOU"),
]

# If a particular row should be hand-set instead of model-derived, add it here.
# Format: id -> (home_p, draw_p, away_p, "comment")
MANUAL_OVERRIDES: dict[str, tuple[float, float, float, str]] = {
    # Example:
    # "M36-WHU-ARS": (0.06, 0.14, 0.80, "Bookmaker (Sky Sports): ARS 2/9"),
}


def _format_row(match_id: str, p: tuple[float, float, float], note: str) -> str:
    h, d, a = p
    return (
        f"  '{match_id}': "
        f"{{ home: {h:.3f}, draw: {d:.3f}, away: {a:.3f} }}, "
        f"// {note}"
    )


def _model_label(use_xg: bool, bayesian: bool) -> str:
    if bayesian:
        return f"PyMC Bayesian (xG={'on' if use_xg else 'off'})"
    return f"Dixon-Coles (xG={'on' if use_xg else 'off'})"


def predict_with_dc(matches: pd.DataFrame, use_xg: bool):
    """Fit DC and return a dict of match_id -> (h, d, a)."""
    print("Fitting Dixon-Coles…")
    model = DixonColesModel(xi=0.0065, use_xg=use_xg).fit(matches)
    print("  ✓ fitted")
    print("Top-5 attack ratings:")
    print(model.ratings().head(5).to_string(index=False))

    out = {}
    for match_id, h, a in REMAINING_FIXTURES:
        out[match_id] = model.predict_outcome(h, a)
    return out


def predict_with_bayes(matches: pd.DataFrame, use_xg: bool):
    """Fit Bayesian model and return a dict of match_id -> (h, d, a).

    Posterior credibility intervals are discarded here — odds.ts only
    holds point probabilities. The model object is available if you
    want richer output.
    """
    from bayesian import BayesianModel
    print("Fitting Bayesian model (this is slow)…")
    model = BayesianModel(use_xg=use_xg).fit(matches, draws=2000, tune=1000)
    print("  ✓ fitted")
    out = {}
    for match_id, h, a in REMAINING_FIXTURES:
        r = model.predict_outcome(h, a)
        out[match_id] = (r["home"], r["draw"], r["away"])
    return out


def write_odds_ts(predictions: dict[str, tuple[float, float, float]],
                  model_label: str) -> None:
    """Render the odds dict into TypeScript and write src/odds.ts."""
    today = dt.date.today().isoformat()
    lines = [
        "// AUTO-GENERATED by model/generate_odds.py — do not hand-edit.",
        "// Manual overrides should go in model/generate_odds.py:MANUAL_OVERRIDES.",
        f"// Model: {model_label}",
        f"// Generated: {today}",
        "",
        "export type MatchProbs = { home: number; draw: number; away: number };",
        "",
        "export const MATCH_PROBABILITIES: Record<string, MatchProbs> = {",
    ]
    for match_id, h, away in REMAINING_FIXTURES:
        if match_id in MANUAL_OVERRIDES:
            ph, pd_, pa, note = MANUAL_OVERRIDES[match_id]
            lines.append(_format_row(match_id, (ph, pd_, pa), f"[manual] {note}"))
        elif match_id in predictions:
            ph, pd_, pa = predictions[match_id]
            # Renormalise just in case (model may sum to 0.999 / 1.001):
            s = ph + pd_ + pa
            ph, pd_, pa = ph / s, pd_ / s, pa / s
            lines.append(_format_row(match_id, (ph, pd_, pa), f"[model] {h} v {away}"))
        else:
            lines.append(f"  // (no prediction for {match_id})")
    lines.append("};")
    lines.append("")
    lines.append("export const WIN_MARGIN_DIST: number[] = [0.50, 0.30, 0.15, 0.05];")
    lines.append("export const DRAW_GOALS_DIST: number[] = [0.32, 0.42, 0.20, 0.06];")
    lines.append("")

    ODDS_TS_PATH.write_text("\n".join(lines))
    print(f"  → wrote {ODDS_TS_PATH.relative_to(ROOT)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-xg", action="store_true", help="Use actual goals, not xG.")
    ap.add_argument("--bayesian", action="store_true", help="Use the slow Bayesian model.")
    ap.add_argument("--no-fetch", action="store_true",
                    help="Skip data fetch; use the cached data/matches.csv.")
    args = ap.parse_args()

    use_xg = not args.no_xg

    cache_path = Path(__file__).parent / "data" / "matches.csv"
    if args.no_fetch and cache_path.exists():
        print(f"Loading cached {cache_path}")
        matches = pd.read_csv(cache_path, parse_dates=["date"])
    else:
        matches = fetch_all()

    if args.bayesian:
        preds = predict_with_bayes(matches, use_xg=use_xg)
    else:
        preds = predict_with_dc(matches, use_xg=use_xg)

    write_odds_ts(preds, _model_label(use_xg, args.bayesian))


if __name__ == "__main__":
    main()
