export const LOGOS: Record<string, string> = {
  ARS: '/logos/arsenal.png',
  AVL: '/logos/villa.png',
  BOU: '/logos/bournemouth.png',
  BUR: '/logos/burnley.png',
  CHE: '/logos/chelsea.png',
  CRY: '/logos/palace.png',
  EVE: '/logos/everton.png',
  LEE: '/logos/leeds.png',
  MUN: '/logos/manutd.png',
  NEW: '/logos/newcastle.png',
  NFO: '/logos/forest.png',
  SUN: '/logos/sunderland.png',
  TOT: '/logos/tottenham.png',
  WHU: '/logos/west_ham.png',
  WOL: '/logos/wolves.png',
};

export const DISPLAY_NAME: Record<string, string> = {
  ARS: 'Arsenal',
  AVL: 'Villa',
  BHA: 'Brighton',
  BOU: 'Bournemouth',
  BRE: 'Brentford',
  BUR: 'Burnley',
  CHE: 'Chelsea',
  CRY: 'Crystal Palace',
  EVE: 'Everton',
  FUL: 'Fulham',
  LEE: 'Leeds',
  LIV: 'Liverpool',
  MCI: 'Man City',
  MUN: 'Man Utd',
  NEW: 'Newcastle',
  NFO: 'Nottm Forest',
  SUN: 'Sunderland',
  TOT: 'Tottenham',
  WHU: 'West Ham',
  WOL: 'Wolves',
};
